name: 'Run on Immage'
description: 'Run a command on current image already published on Digital Ocean'
inputs:
  command:
    description: 'Command to execute'
    required: true
  env:
    description: 'Environment variables'
    required: false    
  accessToken:
    description: 'Digital Ocean API Access Token'
    required: true
  repository:
    description: 'Digital Ocean Repository'
    required: true
runs:
  using: "composite"
  steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ inputs.accessToken }}

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
      
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
        shell: bash
      
      - uses: iamsauravsharma/create-dotenv@v1.2.0
          
      - run: cat .env
        shell: bash
          
      - run: docker run -t --env-file .env registry.digitalocean.com/${{ inputs.repository }}:${{ steps.short-sha.outputs.sha }} ${{ inputs.command }}
        shell: bash
